name: Docker Build & Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/repo-name:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull and run Docker container
        run: |
          docker pull user/repo-name:latest
          docker run -d -p 5000:5000 user/repo-name:latest
